# Generated by Django 4.1.2 on 2022-10-24 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'ordering': ('department_name',),
            },
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ('-device_type',),
            },
        ),
        migrations.CreateModel(
            name='DirectInwardDialIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did', models.IntegerField(unique=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Free', 'Free'), ('Out of Service', 'Out of Service')], default='Free', max_length=20)),
            ],
            options={
                'ordering': ('-did',),
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_number', models.CharField(max_length=50, unique=True)),
                ('employee_name', models.CharField(max_length=250, unique=True)),
                ('employee_status', models.CharField(choices=[('Active', 'Active'), ('In Active', 'In Active')], max_length=15)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_department', to='teldb.department')),
            ],
            options={
                'ordering': ('-employee_name',),
            },
        ),
        migrations.CreateModel(
            name='EmployeeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_category', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Employee Categories',
                'ordering': ('employee_category',),
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'ordering': ('location_name',),
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'ordering': ('organization_name',),
            },
        ),
        migrations.CreateModel(
            name='Telephone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=20, unique=True)),
                ('device_name', models.CharField(max_length=100, unique=True)),
                ('connection_date', models.DateField(blank=True, null=True)),
                ('disconnection_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Installed', 'Installed'), ('In Stock', 'In Stock'), ('In Repair', 'In Repair'), ('Disposed', 'Disposed')], default='In Stock', max_length=20)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teldb.employee')),
                ('code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_code', to='teldb.code')),
                ('extension_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teldb.directinwarddialin')),
                ('telephone_device_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telephone_device_type', to='teldb.devicetype')),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_of_employee', to='teldb.employeecategory'),
        ),
        migrations.AddField(
            model_name='employee',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_location', to='teldb.location'),
        ),
        migrations.AddField(
            model_name='employee',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_organization', to='teldb.organization'),
        ),
    ]
