# Generated by Django 4.1.3 on 2022-11-06 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teldb', '0003_alter_department_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teldb.employeecategory'),
        ),
    ]
