# Generated by Django 4.1.3 on 2022-11-07 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teldb', '0005_alter_department_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telephone',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_to', to='teldb.employee'),
        ),
    ]
